### ISSUE TITLE
I feel that the rule test function is not working properly. x2

### ISSUE THREAD

**Issue by Filipp0vAP** [Karql/elastalert-kibana-plugin#22]
Hello again!

When testing through the plugin, an error occurs:
```
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.

INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 19:27 UTC to 2022-01-19 19:42 UTC: 3178 / 3178 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 19:42 UTC to 2022-01-19 19:57 UTC: 2508 / 2508 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 19:57 UTC to 2022-01-19 20:12 UTC: 1164 / 1164 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 20:12 UTC to 2022-01-19 20:27 UTC: 713 / 713 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 20:27 UTC to 2022-01-19 20:42 UTC: 862 / 862 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 20:42 UTC to 2022-01-19 20:57 UTC: 671 / 671 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 20:57 UTC to 2022-01-19 21:12 UTC: 1008 / 1008 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 21:12 UTC to 2022-01-19 21:27 UTC: 675 / 675 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 21:27 UTC to 2022-01-19 21:42 UTC: 776 / 776 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 21:42 UTC to 2022-01-19 21:57 UTC: 2233 / 2233 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 21:57 UTC to 2022-01-19 22:12 UTC: 3282 / 3282 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 22:12 UTC to 2022-01-19 22:27 UTC: 3163 / 3163 hits

INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-19 22:27 UTC to 2022-01-19 22:42 UTC: 3390 / 3390 hits

WARNING:elasticsearch:DELETE https://elasticsearch:9200/_search/scroll [status:429 request:0.012s]

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/elastalert/elastalert/test_rule.py", line 522, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/opt/elastalert/elastalert/test_rule.py", line 518, in main

    test_instance.run_rule_test()
  File "/opt/elastalert/elastalert/test_rule.py", line 508, in run_rule_test

    self.run_elastalert(rule_yaml, conf)
  File "/opt/elastalert/elastalert/test_rule.py", line 424, in run_elastalert

    client.run_rule(rule, self.endtime, self.starttime)
  File "/opt/elastalert/elastalert/elastalert.py", line 929, in run_rule
    if not self.run_query(rule, rule['starttime'], tmp_endtime):
  File "/opt/elastalert/elastalert/elastalert.py", line 695, in run_query

    self.thread_data.current_es.clear_scroll(scroll_id=scroll_id)
  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/client/__init__.py", line 1289, in clear_scroll

    return self.transport.perform_request(
  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/transport.py", line 318, in perform_request

    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/connection/http_requests.py", line 91, in perform_request

    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/connection/base.py", line 131, in _raise_error

    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1027540516/979.9mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1027539800/979.9mb], new bytes reserved: [716/716b], usages [request=32880/32.1kb, fielddata=0/0b, in_flight_requests=716/716b, model_inference=0/0b, eql_sequence=0/0b, accounting=31592028/30.1mb]')
```

But if you go into the container with ElastAlert and test from it, then everything is OK.
And the rule itself works correctly.

```
/opt/elastalert $ elastalert-test-rule /opt/elastalert/rules/example_new_term.yaml
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
            To send them but remain verbose, use --verbose instead.
Got 352734 hits from the last 0 day

Available terms in first hit:
        SomeHits

INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
1 rules loaded
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:elastalert:Queried rule SampleRuleForTest from 2022-01-20 19:33 UTC to 2022-01-20 19:34 UTC: 199 / 199 hits

Would have written the following documents to writeback index (default is elastalert_status):

elastalert_status - {'rule_name': 'SampleRuleForTest', 'endtime': datetime.datetime(2022, 1, 20, 19, 34, 23, 46411, tzinfo=tzutc()), 'starttime': datetime.datetime(2022, 1, 20, 19, 33, 22, 446411, tzinfo=tzutc()), 'matches': 0, 'hits': 199, '@timestamp': datetime.datetime(2022, 1, 20, 19, 34, 24, 240569, tzinfo=tzutc()), 'time_taken': 0.3048720359802246}
```
Am I doing something wrong, or is the problem on the plugin side?
Thanks!

Kibana 7.16.2
ElastAlert - karql/elastalert2-server:latest

**Comment by Karql** [comment]
@Filipp0vAP 

Are these logs occurred after start elastalert2-server?

These logs for me are not regarding to plugin nor elastalert2-server
but elasticsearch configuration issue:

```
WARNING:elasticsearch:DELETE https://elasticsearch:9200/_search/scroll [status:429 request:0.012s]
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [1027540516/979.9mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1027539800/979.9mb], new bytes reserved: [716/716b], usages [request=32880/32.1kb, fielddata=0/0b, in_flight_requests=716/716b, model_inference=0/0b, eql_sequence=0/0b, accounting=31592028/30.1mb]')
```

How much memory have you assigned to elasticsearch?

https://discuss.elastic.co/t/what-does-this-error-mean-data-too-large-data-for-transport-request/209345
https://stackoverflow.com/a/57822963/11391667

This warning is directly from elastalert2 so eventually you can ask for help on its repo: https://github.com/jertel/elastalert2/discussions

Best regards,
Mateusz
